################################################################################
# Adsorption                                                                   #
#                                                                              #
"""Analyse adsorption in a pore."""
################################################################################

import numpy as np

import poreana.utils as utils


def calculate(link_data, res_cutoff=1, is_normalize=True):
    """This function calculates the values for the adsorption isotherms. This is
    done by counting the number of molecules inside the reservoir and within the
    pore over the whole simulation.

    By normalizing the summation by the number of frames, the resulting value
    is converted to a surface specific concentration inside the pore and volume
    specific concentration within the reservoir.

    The resulting value pair is a point in the adsorption isotherm.

    Parameters
    ----------
    link_data : string
        Link to hdf5, obj or yml file generated by the density sample routine
        :func:`poreana.sample.Sample.init_density`
    res_cutoff : float, optional
        Area of the reservoir to remove from counting on both sides of the
        reservoir
    is_normalize : bool, optional
        True to normalize the number of atoms with the number of frames

    Returns
    -------
    adsorption : dictionary
        Normalized number of molecules outside and inside, and value pair of a
        point on the adsorption isotherm
        :math:`\\left[\\frac{\\text{mmol}}{\\text{l}}\\ ,\\frac{\\mu\\text{mol}}{\\text{m}^2}\\right]`
    """
    sample = utils.load(link_data)

    pore = sample["pore"]
    res = pore["box"]["res"]
    box = list(pore["box"]["dimensions"])
    box[2] -= 2 * res

    shape_ids = [k for k in pore if k.startswith("shape")]

    ex_width = np.array(sample["data"]["ex_width"])
    ex_bins = np.array(sample["data"]["ex"], dtype=float)
    mask = (ex_width >= res_cutoff) & (ex_width <= res - res_cutoff)
    num_ex = float(np.sum(ex_bins[mask]))

    num_in = {pid: float(np.sum(sample["data"][pid]["in"])) for pid in shape_ids}

    inp = sample["inp"]
    num_frames = inp["num_frame"]
    entry = inp["entry"]

    if is_normalize:
        num_ex /= num_frames
        num_in = {pid: v / num_frames for pid, v in num_in.items()}

    surface = {
        pid: 2 * np.pi * (pore[pid]["diam"] / 2) * (box[2] - 2 * entry)
        for pid in shape_ids
    }
    volume = 2 * (res - 2 * res_cutoff) * box[0] * box[1]

    conc = {
        pid: {"mumol_m2": utils.mols_to_mumol_m2(num_in[pid], surface[pid])}
        for pid in shape_ids
    }
    conc["mmol_l"] = utils.mols_to_mmol_l(num_ex, volume)

    return {"conc": conc, "num": {"ex": num_ex, **num_in}}
