################################################################################
# Angle                                                                        #
#                                                                              #
"""Analyse the molecule angle in a pore."""
################################################################################

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

import poreana.utils as utils


def bins_plot(
    data_link_angle,
    data_link_dens,
    pore_id="shape_00",
    intent="",
    is_mean=False,
    is_norm=False,
    kwargs={},
):
    """This function plots the angle. If an intent is given instead, only a
    plot-function will be called. Available options for ``intent`` are

    * empty string - Create subplots for the density inside and outside the pore
    * **in** - Create plot for the density inside pore
    * **ex** - Create plot for the density outside pore

    Parameters
    ----------
    data_link_angle : string
        Link to angle data object generated by the sample routine
        :func:`poreana.sample.Sample.init_angle`
    data_link_dens : string
        Link to density hdf5, obj or yml data file generated by the sample routine
        :func:`poreana.sample.Sample.init_density`
    pore_id : string, optional
        Pore shape identifier when multiple shapes are present
    intent : string, optional
        Intent for plotting — empty, **in**, or **ex**
    is_mean : bool, optional
        True to plot mean values
    is_norm : bool, optional
        True to normalize x-axis
    kwargs : dict, optional
        Dictionary with plotting parameters (only with given intent)

    Returns
    -------
    mean : dictionary
        Mean value of the angle inside and outside the pore
    """
    agl = utils.load(data_link_angle)
    dens = utils.load(data_link_dens)

    is_pore = "pore" in agl

    width_in_raw = (
        np.array(agl["data"][pore_id]["in_width"][:-1]) if is_pore else np.array([])
    )
    width_ex_raw = np.array(agl["data"]["ex_width"])

    if is_norm:
        width_in = (
            width_in_raw / width_in_raw[-1] if len(width_in_raw) else width_in_raw
        )
        width_ex = width_ex_raw / width_ex_raw[-1]
    else:
        width_in = width_in_raw
        width_ex = width_ex_raw

    dens_in = np.array(dens["data"][pore_id]["in"]) if is_pore else np.array([])
    dens_ex = np.array(dens["data"]["ex"])
    agl_in = np.array(agl["data"][pore_id]["in"]) if is_pore else np.array([])
    agl_ex = np.array(agl["data"]["ex"])

    angle_in = (
        np.where(dens_in != 0, agl_in / dens_in, 0.0) if is_pore else np.array([])
    )
    angle_ex = np.where(dens_ex != 0, agl_ex / dens_ex, 0.0)

    mean = {}
    if is_pore and len(angle_in):
        mean["in"] = float(np.mean(angle_in))
    mean["ex"] = float(np.mean(angle_ex))

    if not intent:
        if is_pore:
            plt.subplot(211)
            sns.lineplot(x=width_in, y=angle_in)
            if is_mean:
                sns.lineplot(x=width_in, y=np.full_like(width_in, mean["in"]))
            plt.xlim([0, width_in[-1]])
            plt.xlabel("Distance from pore center (nm)")
            plt.ylabel("Angle (deg)")
            plt.legend(["Angle", "Mean"])

        plt.subplot(212)
        sns.lineplot(x=width_ex, y=angle_ex)
        if is_mean:
            sns.lineplot(x=width_ex, y=np.full_like(width_ex, mean["ex"]))
        plt.xlim([0, width_ex[-1]])
        plt.xlabel("Distance from reservoir end (nm)")
        plt.ylabel("Angle (deg)")
        plt.legend(["Angle", "Mean"])

    else:
        if intent not in ["in", "ex"]:
            print("Invalid intent. Check documentation for available options.")
            return

        if intent == "in":
            sns.lineplot(x=width_in, y=angle_in, **kwargs)
            plt.xlim([0, width_in[-1]])
        else:
            sns.lineplot(x=width_ex, y=angle_ex, **kwargs)
            plt.xlim([0, width_ex[-1]])

    return mean
