################################################################################
# Gyration                                                                     #
#                                                                              #
"""Analyse gyration radius in a pore."""
################################################################################

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

import poreana.utils as utils


def bins_plot(
    data_link_gyr,
    data_link_dens,
    intent="",
    pore_id="shape_00",
    is_mean=False,
    is_norm=False,
    kwargs={},
):
    """This function plots the gyration radius. If an intent is given instead,
    only a plot-function will be called. Available options for ``intent`` are

    * empty string - Create subplots for the density inside and outside the pore
    * **in** - Create plot for the density inside pore
    * **ex** - Create plot for the density outside pore

    Parameters
    ----------
    data_link_gyr : string
        Link to gyration data object generated by the sample routine
        :func:`poreana.sample.Sample.init_gyration`
    data_link_dens : string
        Link to density hdf5, obj or yml data file generated by the sample routine
        :func:`poreana.sample.Sample.init_density`
    intent : string, optional
        Intent for plotting - empty, **in**, or **ex**
    pore_id : string, optional
        Pore shape identifier when multiple shapes are present
    is_mean : bool, optional
        True to plot mean values
    is_norm : bool, optional
        True to normalize x-axis
    kwargs : dict, optional
        Dictionary with plotting parameters (only with given intent)

    Returns
    -------
    mean : dictionary
        Mean value of the radius of gyration inside and outside the pore in nm
    """
    gyr = utils.load(data_link_gyr)
    dens = utils.load(data_link_dens)

    is_pore = "pore" in gyr

    width_in_raw = (
        np.array(gyr["data"][pore_id]["in_width"][:-1]) if is_pore else np.array([])
    )
    width_ex_raw = np.array(gyr["data"]["ex_width"])

    if is_norm:
        width_in = (
            width_in_raw / width_in_raw[-1] if len(width_in_raw) else width_in_raw
        )
        width_ex = width_ex_raw / width_ex_raw[-1]
    else:
        width_in = width_in_raw
        width_ex = width_ex_raw

    dens_in = np.array(dens["data"][pore_id]["in"]) if is_pore else np.array([])
    dens_ex = np.array(dens["data"]["ex"])
    gyr_in = np.array(gyr["data"][pore_id]["in"]) if is_pore else np.array([])
    gyr_ex = np.array(gyr["data"]["ex"])

    gyration_in = (
        np.where(dens_in != 0, gyr_in / dens_in, 0.0) if is_pore else np.array([])
    )
    gyration_ex = np.where(dens_ex != 0, gyr_ex / dens_ex, 0.0)

    mean = {}
    if is_pore and len(gyration_in):
        mean["in"] = float(np.mean(gyration_in))
    mean["ex"] = float(np.mean(gyration_ex))

    if not intent:
        if is_pore:
            plt.subplot(211)
            sns.lineplot(x=width_in, y=gyration_in)
            if is_mean:
                sns.lineplot(x=width_in, y=np.full_like(width_in, mean["in"]))
            plt.xlim([0, width_in[-1]])
            plt.xlabel("Distance from pore center (nm)")
            plt.ylabel("Radius (nm)")
            plt.legend(["Gyration radius", "Mean"])

        plt.subplot(212)
        sns.lineplot(x=width_ex, y=gyration_ex)
        if is_mean:
            sns.lineplot(x=width_ex, y=np.full_like(width_ex, mean["ex"]))
        plt.xlim([0, width_ex[-1]])
        plt.xlabel("Distance from reservoir end (nm)")
        plt.ylabel("Radius (nm)")
        plt.legend(["Gyration radius", "Mean"])

    else:
        if intent not in ["in", "ex"]:
            print("Invalid intent. Check documentation for available options.")
            return

        if intent == "in":
            sns.lineplot(x=width_in, y=gyration_in, **kwargs)
            plt.xlim([0, width_in[-1]])
        else:
            sns.lineplot(x=width_ex, y=gyration_ex, **kwargs)
            plt.xlim([0, width_ex[-1]])

    return mean
