################################################################################
# Tables                                                                       #
#                                                                              #
"""Print analysis information in table form."""
################################################################################

import pandas as pd

import poreana.diffusion as diffusion
import poreana.utils as utils


###############################
# MC - Diffusion, Free Energy #
###############################
def mc_model(link, print_con=False):
    """This function prints the model inputs of the calculation.

    Parameters
    ----------
    link : string
        Link to the diffusion hdf5, obj or yml data file generated by the MC Algorithm function
        :func:`poreana.mc.MC.run`
    print_con: bool, optional
        True for printing in console

    Returns
    -------
    df_model: obj
        Data frame of the model inputs
    """
    # Load Results from the output object file
    data = utils.load(link)

    # Load model inputs
    model = data["model"]
    bin_number = model["bin number"]
    len_step = model["len_step"]
    len_frame = model["len_frame"]
    frame_num = model["num_frame"]
    nD = model["nD"]
    nF = model["nF"]
    nDrad = model["nDrad"]
    d = model["guess"]
    model_string = model["model"]
    pbc = model["pbc"]
    direction = int(model["direction"])

    # String for pbc
    pbc = pbc == 1

    # String for system
    system = "pore" if "pore" in data else "box"

    # Len step string
    len_step_string = ", ".join(str(step) for step in len_step)

    # Dictionary for model inputs
    data = [
        str("%.i" % bin_number),
        len_step_string,
        str("%.2e" % (len_frame * 10 ** (-12))),
        str("%.i" % frame_num),
        str("%.i" % nD),
        str("%.i" % nF),
        str("%.i" % nDrad),
        model_string,
        str("%.2e" % (d * 10 ** (-6))),
        system,
        pbc,
        str("%.i" % direction),
    ]
    df_model = pd.DataFrame(
        data,
        index=list(
            [
                "Bin number",
                "step length",
                "frame length (s)",
                "frame number",
                "nD",
                "nF",
                "nDrad",
                "model",
                "guess diffusion (m2/s-1)",
                "system",
                "pbc",
                "direction",
            ]
        ),
        columns=list(["Input"]),
    )

    if print_con:
        print("\nModel Inputs")
        print(df_model)

    return df_model


def mc_inputs(link, print_con=False):
    """This function prints the MC Algorithm inputs of the calculation.

    Parameters
    ----------
    link : string
        Link to the diffusion hdf5, obj or yml data file generated by the MC Algorithm function
        :func:`poreana.mc.MC.run`
    print_con : bool, optional
        True for printing in console

    Returns
    -------
    df_mc : obj
        Data frame of the MC Alogrithm inputs
    """
    # Load Results from the output object file
    data = utils.load(link)

    # Read MC inputs
    inp = data["inp"]
    nmc_eq = inp["MC steps eq"]
    nmc = inp["MC steps"]
    num_mc_update = inp["step width update"]
    print_freq = inp["print freq"]
    temp = inp["temperature"]

    # Table for MC Inputs
    data = [
        str("%.i" % nmc_eq),
        str("%.i" % nmc),
        temp,
        str("%.i" % num_mc_update),
        str("%.i" % print_freq),
    ]
    df_mc = pd.DataFrame(
        data,
        index=list(
            [
                "MC steps (Equilibrium)",
                "MC steps (Production)",
                "temperature (MC)",
                "movewidth update frequency",
                "print frequency",
            ]
        ),
        columns=list(["Input"]),
    )

    if print_con:
        print("\nMC Inputs")
        print(df_mc)

    return df_mc


def mc_results(
    link, print_con=False, sections={"box": [], "pore": [], "res": []}, len_step=[]
):
    """This function prints the MC results of the diffusion calculation.
    Different areas are defined in the **sections** dectionary. Standard areas
    are calculated by leaving the value list empty

    * **box** - For the entire system
    * **pore** - Pore section (only for pore systems)
    * **res** - Resercoir section (only for pore systems)

    Parameters
    ----------
    link : string
        Link to the diffusion hdf5, obj or yml data file generated by the MC Algorithm
        function :func:`poreana.mc.MC.run`
    print_con : bool, optional
        True for printing in console
    sections : dictionary, optinal
        Sections for diffusion calculation

    Returns
    -------
    df_mc_results : DataFrame
        Data frame of the MC Alogrithm inputs
    """
    # Load data
    data = utils.load(link)
    model = data["model"]

    # Process input
    len_step = list(model["len_step"]) if not len_step else len_step

    # Extract system data
    box_z = (
        round(data["pore"]["box"]["dimensions"][2], 2)
        if "pore" in data
        else round(data["box"]["length"][2], 2)
    )
    res = round(data["pore"]["box"]["res"], 2) if "pore" in data else 0

    # Run through sections
    diff_dict = {}
    for key, section in sections.items():
        # Process special cases
        if not section:
            if key == "box":
                area = [0, box_z]
            elif key == "pore":
                area = [res, round(box_z - res, 2)] if "pore" in data else []
            elif key == "res":
                area = [0, res] if "pore" in data else []
            else:
                print('The area of "' + key + '" needs to be specified')
                return
        else:
            area = section

        # Calculate diffusion in area
        if area:
            diff = diffusion.mc_fit(
                link, section=area, is_print=False, is_plot=False, len_step=len_step
            )
            diff_dict[key] = {
                "Area (nm)": area,
                "Diffusion (10^-9 m^2s^-1)": diff[0],
                "Residual (10^-9 m2s^-1)": diff[3],
            }

    # Create pandas table
    df_mc_results = pd.DataFrame.from_dict(diff_dict, orient="index")

    if print_con:
        print("\nMC Results")
        print(df_mc_results)

    return df_mc_results
